version : '3'
services:
  mysql-db:
    image: mysql:latest
    container_name: MySQL
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root123
    ports:
      - 3306:3306


  spring-boot-app:
    build:
      context: ./spring-app
    container_name: SpringApp
    depends_on:
      - mysql-db
    restart: on-failure
    ports:
      - 8082:8082
    volumes:
      - spring-data:/app/data
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql-db:3306/devops?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root123",
        "spring.jpa.show-sql" : "true",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
          }'

  nginx-app:
    build:
      context: ./nginx
    container_name: NginxFrontend
    ports:
      - 80:80
    depends_on :
      - spring-boot-app
    restart : on-failure




volumes:
  spring-data: